[package]
name = "editormd"
version = "0.0.1"
description = "Editor Markdown WYSIWYG ligero y multiplataforma"
authors = ["Ismael Caballero"]
license = "MIT"
repository = ""
edition = "2024"
rust-version = "1.90"


[lib]
name = "editormd_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-log = "2"
